FROM ubuntu:22.04

COPY ./sources.list /etc/apt/sources.list

RUN && apt-get update \
    && apt-get install libopencv-dev clang libclang-dev curl build-essential gcc make \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
