on:
    push:
      branches:
      - master
      - main
    pull_request:
      branches:
      - master 
      - main
      
name: CI
  
jobs:
    lint:
      name: Lint and Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          name: Checkout 🛎️
        - uses: actions-rs/toolchain@v1
          name: Setup Cargo Toolchain 🛎️
          with:
            components: rustfmt, clippy
        - uses: actions-rs/cargo@v1
          name: Running Tests 🚀
          with:
            command: test
            args: --all-features
            working-directory: ./RayTracer
        - uses: actions-rs/cargo@v1
          name: Check Code Format 🔧
          with:
            command: fmt
            args: -- --check
            working-directory: ./RayTracer
        - uses: actions-rs/cargo@v1
          name: Lint with Clippy 🔧
          with:
            command: clippy
            args: --all-targets --all-features -- -D warnings
            working-directory: ./RayTracer
    build:
      name: Build and Upload
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          name: Checkout 🛎️
        - uses: actions-rs/toolchain@v1
          name: Setup Cargo Toolchain 🛎️
        - name: Download Dependencies 🛎️
          run: wget https://github.com/google/fonts/blob/main/ofl/encodesans/EncodeSans%5Bwdth%2Cwght%5D.ttf
        - uses: actions-rs/cargo@v1
          name: Build 🔧
          with:
            command: build
            args: --release --all-features
            working-directory: ./RayTracer
        - uses: actions-rs/cargo@v1
          name: Run 🔧
          with:
            command: run
            args: --release
            working-directory: ./RayTracer
        - uses: actions/upload-artifact@v2
          name: Upload Artifacts 🚀
          with:
            name: output
            path: output/
            working-directory: ./RayTracer